#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np
import re
import string

import ast
import csv
from collections import Counter
from stop_words import get_stop_words


def prune(text):
    translator = str.maketrans('', '', string.punctuation)
    words = text.translate(translator).lower().split()
    stop_words = get_stop_words('english')
    pruned_words = [w for w in words if w not in stop_words]
    return pruned_words
    

with open('movie_data.csv', 'r') as f:
    reader = list(csv.DictReader(f))

    genres = np.concatenate(
            [ast.literal_eval(row['genres']) for row in reader]
            )

    """
    Five most common genres

    """
    counts = Counter(genres)
    print(counts.most_common(5))

    popular_genres = [name for name, counts in counts.most_common(5)]

    popular_words = ''.join([
            prune(row['summary']) for row in reader
            if bool(
                set(ast.literal_eval(row['genres'])) &
                set(popular_genres)
                )
            ])

    """
    Twenty most common words for five most popular genres

    """
    print(Counter(popular_words).most_common(20))
